project:
  type: website
  output-dir: docs

website:
  title: 'psychiatry-residents'
  navbar:
    left:
      - href: index.qmd
        text: Neuropsychological Testing for Psychiatrists
      # - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
